name: Release saferun

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux-x86_64
            os: ubuntu-latest
            binary_name: saferun
            asset_name: saferun-linux-x86_64
          
          - name: macos-x86_64
            os: macos-13
            binary_name: saferun
            asset_name: saferun-macos-x86_64

          - name: macos-aarch64
            os: macos-latest
            binary_name: saferun
            asset_name: saferun-macos-aarch64

          - name: windows-x86_64
            os: windows-latest
            binary_name: saferun.exe
            asset_name: saferun-windows-x86_64.exe

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build release binary 
        uses: cargo build --release

      - name: Prepare asset folder (Unix)
        if: runner.os != 'Windows'
        run: |
          mkdir dist
          cp target/release/${{ matrix.platform.binary_name }} dist/${{ matrix.platform.asset_name }}

      - name: Preapre asset folder (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path dist
          Copy-Item "target/release/${{ matrix.platform.binary_name }}" "dist/${{ matrix.platform.asset_name }}"

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
